name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: vinay0410/tectonic-action@master
        env: 
          ${{ secrets.GITHUB_TOKEN }}
        with:
          tex_path: 'dafirebanks_resume-openfont.tex'
          push: 'yes'
